# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemno', models.IntegerField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=64, null=True)),
                ('cost', models.FloatField(null=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
