# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemno',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
