# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whtech', '0002_auto_20161113_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
